### ISSUE TITLE
multi-gpu lora finetune falcon

### ISSUE THREAD

**Issue by acadaiaca** [rmihaylov/falcontune#4]
Whether to support multi-gpu lora fine-tuning falcon? thx!

**Comment by codybum** [comment]
Multi-gpu would be good.  Accelerate is used, which helps with multi-gpu.  Is there as reason why multi-gpu is not an option already?

**Comment by 631068264** [comment]
https://github.com/rmihaylov/falcontune/issues/7

**Comment by praveenkanithi** [comment]
Falcontune uses RefinedWeb to instantiate a model of type RefinedWebModel, which I think is causing issues with multiple gpus. When I built the code after replacing RefinedWebModel with AutoModelForCausalLLM in 'load_model' function, it worked on multiple gpus without any issues.

**Comment by codybum** [comment]
@praveenkanithi does falcontune work the replacement or are you saying the training code works with other models supported by refinedwebmodel?  If it works, is it a simple search and replace?

**Comment by praveenkanithi** [comment]
It's the first one. I'm just talking about how I fixed the issue of running Falcon on multiple gpus.

**Comment by codybum** [comment]
@praveenkanithi that is great, I would very much like to get falcontune working with multi-gpu.  I replaced RefinedWebModel with AutoModelForCausalLLM and now I see: "You are using a model of type RefinedWeb to instantiate a model of type AutoModelForCausalLLM. This is not supported for all configurations of models and can yield errors.", seems like I am headed in the right direction.

However, after mapping I immediately get the error: "ValueError: Pointer argument (at 1) cannot be accessed from Triton (cpu tensor?)"

Here are my parameters:
Parameters:
-------config-------
dataset='./alpaca_data_cleaned.json'
data_type='alpaca'
lora_out_dir='.models/checkpoints/falcon-40b-instruct-4bit-alpaca/'
lora_apply_dir=None
weights='./models/falcon/gptq_model-4bit--1g.safetensors'
target_modules=['query_key_value']

------training------
mbatch_size=1
batch_size=2
gradient_accumulation_steps=2
epochs=3
lr=0.0003
cutoff_len=256
lora_r=8
lora_alpha=16
lora_dropout=0.05
val_set_size=0.2
gradient_checkpointing=False
gradient_checkpointing_ratio=1
warmup_steps=5
save_steps=50
save_total_limit=3
logging_steps=5
checkpoint=False
skip=False
world_size=1
ddp=False
device_map='auto'

I have tried messing with the world size to enable ddp, but that created other issues.  I am running with the following command:

falcontune finetune \
    --model=falcon-40b-instruct-4bit \
    --weights=./models/falcon/gptq_model-4bit--1g.safetensors \
    --dataset=./alpaca_data_cleaned.json \
    --data_type=alpaca \
    --lora_out_dir=.models/checkpoints/falcon-40b-instruct-4bit-alpaca/ \
    --backend=triton \
    --mbatch_size=1 \
    --batch_size=2 \
    --epochs=3 \
    --lr=3e-4 \
    --cutoff_len=256 \
    --lora_r=8 \
    --lora_alpha=16 \
    --lora_dropout=0.05 \
    --warmup_steps=5 \
    --save_steps=50 \
    --save_total_limit=3 \
    --logging_steps=5 \
    --target_modules='["query_key_value"]'

**Comment by zepmck** [comment]
Any update on this? Tnx

**Comment by praveenkanithi** [comment]
@codybum, can you give me the full error and where are you getting this error?

FYI, I'm not running falcontune as they specified in this repository. Instead of installing this repository using `setup.py`, I made a few changes for falcontune imports (you need to do it in multiple files), so I can run using `python ./falcontune/run.py` with appropriate arguments.

**Comment by codybum** [comment]
@praveenkanithi If its not too much trouble perhaps you can post a working fork?

Here is the full error:

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cuda118.so
/usr/local/lib/python3.10/dist-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/nvidia/lib64'), PosixPath('/usr/local/nvidia/lib')}
  warn(msg)
/usr/local/lib/python3.10/dist-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: /usr/local/nvidia/lib:/usr/local/nvidia/lib64 did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
/usr/local/lib/python3.10/dist-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/usr/local/cuda/lib64/libcudart.so'), PosixPath('/usr/local/cuda/lib64/libcudart.so.11.0')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.0
CUDA SETUP: Detected CUDA version 118
CUDA SETUP: Loading binary /usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cuda118.so...
You are using a model of type RefinedWeb to instantiate a model of type AutoModelForCausalLLM. This is not supported for all configurations of models and can yield errors.
The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.
The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.
The safetensors archive passed at models/falcon-40b-instruct-4bit/gptq_model-4bit--1g.safetensors does not contain metadata. Make sure to save your model with the `save_pretrained` method. Defaulting to 'pt' metadata.
                                                                                                                                                                                       
Parameters:
-------config-------
dataset='pathicd-large-v1-train-cancer_falcon.json'
data_type='alpaca'
lora_out_dir='custom-falcon-40b_pathicd-large-v1-train-cancer_epochs1-4bit'
lora_apply_dir=None
weights='models/falcon-40b-instruct-4bit/gptq_model-4bit--1g.safetensors'
target_modules=['query_key_value']

------training------
mbatch_size=1
batch_size=2
gradient_accumulation_steps=2
epochs=1
lr=0.0003
cutoff_len=256
lora_r=8
lora_alpha=16
lora_dropout=0.05
val_set_size=0.2
gradient_checkpointing=False
gradient_checkpointing_ratio=1
warmup_steps=5
save_steps=50
save_total_limit=3
logging_steps=5
checkpoint=False
skip=False
world_size=1
ddp=False
device_map='auto'


Converted as Half.
trainable params: 8355840 || all params: 1075691520 || trainable%: 0.7767877541695225
Found cached dataset json (/root/.cache/huggingface/datasets/json/default-0181237cb7d9e7a7/0.0.0/8bb11242116d547c741b2e8a1f18598ffdd40a1d4f2a2872c7a28b697434bc96)
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 536.91it/s]
Loading cached split indices for dataset at /root/.cache/huggingface/datasets/json/default-0181237cb7d9e7a7/0.0.0/8bb11242116d547c741b2e8a1f18598ffdd40a1d4f2a2872c7a28b697434bc96/cache-2956635c10ad56da.arrow and /root/.cache/huggingface/datasets/json/default-0181237cb7d9e7a7/0.0.0/8bb11242116d547c741b2e8a1f18598ffdd40a1d4f2a2872c7a28b697434bc96/cache-c7be19ca6dfe40e6.arrow
Run eval every 4148 steps                                                                                                                                                              
Found safetensors installation, but --save_safetensors=False. Safetensors should be a preferred weights saving format due to security and performance reasons. If your model cannot be saved by safetensors please feel free to open an issue at https://github.com/huggingface/safetensors!
PyTorch: setting up devices
The default value for the training argument `--report_to` will change in v5 (from all installed integrations to none). In v5, you will need to use `--report_to all` to get the same behavior as now. You should start updating your code and make this info disappear :-).
You have loaded a model on multiple GPUs. `is_model_parallel` attribute will be force-set to `True` to avoid any unexpected behavior such as device placement mismatching.
git root error: Cmd('git') failed due to: exit code(128)
  cmdline: git rev-parse --show-toplevel
  stderr: 'fatal: detected dubious ownership in repository at '/workspace'
To add an exception for this directory, call:

	git config --global --add safe.directory /workspace'
The following columns in the training set don't have a corresponding argument in `PeftModelForCausalLM.forward` and have been ignored: token_type_ids, input, instruction, output. If token_type_ids, input, instruction, output are not expected by `PeftModelForCausalLM.forward`,  you can safely ignore this message.
***** Running training *****
  Num examples = 33,190
  Num Epochs = 1
  Instantaneous batch size per device = 1
  Total train batch size (w. parallel, distributed & accumulation) = 2
  Gradient Accumulation steps = 2
  Total optimization steps = 16,595
  Number of trainable parameters = 8,355,840
Automatic Weights & Biases logging enabled, to disable set os.environ["WANDB_DISABLED"] = "true"
  0%|                                                                                                                                                        | 0/16595 [00:00<?, ?it/s]You're using a PreTrainedTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
Traceback (most recent call last):
  File "<string>", line 21, in matmul_248_kernel
KeyError: ('2-.-0-.-0-83ca8b715a9dc5f32dc1110973485f64-d6252949da17ceb5f3a278a70250af13-3b85c7bef5f0a641282f3b73af50f599-3d2aedeb40d6d81c66a42791e268f98b-3498c340fd4b6ee7805fd54b882a04f5-e1f133f98d04093da2078dfc51c36b72-b26258bf01f839199e39d64851821f26-d7c06e3b46e708006c15224aac7a1378-f585402118c8a136948ce0a49cfe122c', (torch.float16, torch.int32, torch.float16, torch.float16, torch.int32, torch.int32, 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32'), (256, 64, 32, 8), (True, True, True, True, True, True, (False, False), (True, False), (True, False), (False, False), (False, False), (True, False), (False, True), (True, False), (False, True), (True, False), (False, True), (True, False), (True, False)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/falcontune", line 33, in <module>
    sys.exit(load_entry_point('falcontune==0.1.0', 'console_scripts', 'falcontune')())
  File "/usr/local/lib/python3.10/dist-packages/falcontune-0.1.0-py3.10.egg/falcontune/run.py", line 87, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/falcontune-0.1.0-py3.10.egg/falcontune/finetune.py", line 162, in finetune
    trainer.train()
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1645, in train
    return inner_training_loop(
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1938, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 2759, in training_step
    loss = self.compute_loss(model, inputs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 2784, in compute_loss
    outputs = model(**inputs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/operations.py", line 581, in forward
    return model_forward(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/operations.py", line 569, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/usr/local/lib/python3.10/dist-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/peft/peft_model.py", line 678, in forward
    return self.base_model(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/falcontune-0.1.0-py3.10.egg/falcontune/model/falcon/model.py", line 1078, in forward
    transformer_outputs = self.transformer(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/falcontune-0.1.0-py3.10.egg/falcontune/model/falcon/model.py", line 973, in forward
    outputs = block(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/falcontune-0.1.0-py3.10.egg/falcontune/model/falcon/model.py", line 641, in forward
    attn_outputs = self.self_attention(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/falcontune-0.1.0-py3.10.egg/falcontune/model/falcon/model.py", line 493, in forward
    fused_qkv = self.query_key_value(hidden_states)  # [batch_size, seq_length, 3 x hidden_size]
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/falcontune-0.1.0-py3.10.egg/falcontune/model/lora.py", line 59, in forward
    result = self.quant_instance.forward(x)
  File "/usr/local/lib/python3.10/dist-packages/falcontune-0.1.0-py3.10.egg/falcontune/backend/triton/quantlinear.py", line 13, in forward
    out = AutogradMatmul.apply(
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/amp/autocast_mode.py", line 103, in decorate_fwd
    return fwd(*_cast(args, cast_inputs), **_cast(kwargs, cast_inputs))
  File "/usr/local/lib/python3.10/dist-packages/falcontune-0.1.0-py3.10.egg/falcontune/backend/triton/autograd.py", line 11, in forward
    output = tu.triton_matmul(x, qweight, scales, qzeros, g_idx, bits, maxq)
  File "/usr/local/lib/python3.10/dist-packages/falcontune-0.1.0-py3.10.egg/falcontune/backend/triton/triton_utils.py", line 246, in triton_matmul
    matmul_248_kernel[grid](input, qweight, output,
  File "/usr/local/lib/python3.10/dist-packages/falcontune-0.1.0-py3.10.egg/falcontune/backend/triton/custom_autotune.py", line 97, in run
    timings = {config: self._bench(*args, config=config, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/falcontune-0.1.0-py3.10.egg/falcontune/backend/triton/custom_autotune.py", line 97, in <dictcomp>
    timings = {config: self._bench(*args, config=config, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/falcontune-0.1.0-py3.10.egg/falcontune/backend/triton/custom_autotune.py", line 79, in _bench
    return triton.testing.do_bench(kernel_call, rep=40, **bench_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/triton/testing.py", line 143, in do_bench
    fn()
  File "/usr/local/lib/python3.10/dist-packages/falcontune-0.1.0-py3.10.egg/falcontune/backend/triton/custom_autotune.py", line 70, in kernel_call
    self.fn.run(*args, num_warps=config.num_warps, num_stages=config.num_stages, **current)
  File "<string>", line 43, in matmul_248_kernel
ValueError: Pointer argument (at 1) cannot be accessed from Triton (cpu tensor?)

**Comment by codybum** [comment]
@praveenkanithi Here is the Dockerfile I am using to build the environment.  

FROM nvidia/cuda:11.8.0-devel-ubuntu22.04
ENV PYTHONUNBUFFERED=1 
ENV TORCH_CUDA_ARCH_LIST="3.5;5.0;6.0;6.1;7.0;7.5;8.0;8.6+PTX"

# SYSTEM
RUN apt-get update --yes --quiet && DEBIAN_FRONTEND=noninteractive apt-get install --yes --quiet --no-install-recommends \
    software-properties-common \
    build-essential apt-utils \
    python3-dev \
    python3-pip \
    wget curl vim git ca-certificates kmod \
 && rm -rf /var/lib/apt/lists/*


RUN git clone https://github.com/rmihaylov/falcontune.git
RUN mv falcontune /workspace
WORKDIR /workspace

RUN pip install --upgrade pip
COPY requirements_update.txt /workspace/requirements_update.txt
RUN pip install -r requirements_update.txt 
RUN python3 setup.py install         

RUN pip install ninja
RUN python3 setup_cuda.py install 
RUN pip install scipy
